# Get Program Files root to lookup possible LLVM installation
file(TO_CMAKE_PATH "$ENV{ProgramW6432}/LLVM/bin" LLVM_BIN_DIR)

# Set NO_DEFAULT_PATH to prevent the toolchain from picking up the copy of LLVM which ships with
# Visual Studio, which may be outdated
find_program(CLANG_C_EXECUTABLE NAMES "clang.exe" PATHS ${LLVM_BIN_DIR} NO_DEFAULT_PATH REQUIRED)
find_program(CLANG_CXX_EXECUTABLE NAMES "clang++.exe" PATHS ${LLVM_BIN_DIR} NO_DEFAULT_PATH REQUIRED)
find_program(CLANG_RC_EXECUTABLE NAMES "llvm-rc.exe" PATHS ${LLVM_BIN_DIR} NO_DEFAULT_PATH REQUIRED)
find_program(CLANG_LLD_EXECUTABLE NAMES "lld-link.exe" PATHS ${LLVM_BIN_DIR} NO_DEFAULT_PATH REQUIRED)

set(CMAKE_C_COMPILER ${CLANG_C_EXECUTABLE} CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER ${CLANG_CXX_EXECUTABLE} CACHE STRING "" FORCE)
set(CMAKE_RC_COMPILER  ${CLANG_RC_EXECUTABLE} CACHE STRING "" FORCE)
set(CMAKE_LINKER ${CLANG_LLD_EXECUTABLE} CACHE STRING "" FORCE)

set(VCPKG_POLICY_SKIP_ARCHITECTURE_CHECK enabled)
set(VCPKG_POLICY_SKIP_DUMPBIN_CHECKS enabled)
set(VCPKG_LOAD_VCVARS_ENV ON)

set(VCPKG_C_FLAGS "-arch:AVX")
set(VCPKG_CXX_FLAGS "${VCPKG_C_FLAGS}")
