name: Build packages

on:
  push: 
    branches:
      - main
  pull_request:

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap vcpkg
        run: ./scripts/bootstrap.ps1
      - name: Install libobjc2
        run: ./vcpkg install libobjc2:x64-windows-llvm
      - uses: actions/upload-artifact@v4
        with:
          name: installed
          path: ./installed
      - uses: actions/upload-artifact@v4
        with:
          name: buildtrees
          path: ./buildtrees

  ubuntu-22.04:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: apt-get install -y clang
      - name: Bootstrap vcpkg
        run: ./bootstrap-vcpkg.sh
      - name: Install libobjc2
        run: ./vcpkg install libobjc2:x64-windows-llvm
      - uses: actions/upload-artifact@v4
        with:
          name: installed
          path: ./installed
      - uses: actions/upload-artifact@v4
        with:
          name: buildtrees
          path: ./buildtrees
