name: Build packages

on:
  push: 
    branches:
      - main
  pull_request:

jobs:
  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap vcpkg
        run: ./scripts/bootstrap.ps1
      - name: Install libobjc2
        run: ./vcpkg install libobjc2:x64-windows-llvm
      - name: Install gnustep-make
        run: ./vcpkg install gnustep-make:x64-windows-llvm
      - name: Install libffi
        run: ./vcpkg install libffi:x64-windows-llvm
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: installed-windows
          path: ./installed
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: buildtrees-windows
          path: ./buildtrees

  linux:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-22.04
            image: ubuntu:22.04
            family: ubuntu
          - name: ubuntu-24.04
            image: ubuntu:24.04
            family: ubuntu
          - name: rockylinux-9
            image: rockylinux:9
            family: rhel
          - name: rockylinux-8
            image: rockylinux:8
            family: rhel
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (Ubuntu)
        run: |
          apt-get update
          apt-get install -y clang curl zip unzip tar git pkg-config make
        if: matrix.family == 'ubuntu'
      - name: Install dependencies (Enterprise Linux)
        run: |
          yum install -y clang zip unzip tar git pkg-config which
        if: matrix.family == 'rhel'
      - name: Bootstrap vcpkg
        run: ./bootstrap-vcpkg.sh
      - name: Install libobjc2
        run: ./vcpkg install libobjc2:x64-linux-llvm
      - name: Install gnustep-make
        run: ./vcpkg install gnustep-make:x64-linux-llvm
      - name: Install dependencies (Ubuntu)
        run: |
          apt-get update
          apt-get install -y libxml2-dev libxslt-dev libcurl4-gnutls-dev gnutls-dev
        if: matrix.family == 'ubuntu'
      - name: Install dependencies (Enterprise Linux)
        run: |
          yum install -y libxml2-devel libxslt-devel libcurl-devel gnutls-devel libffi-devel libicu-devel
        if: matrix.family == 'rhel'
      - name: Install gnustep-base
        run: ./vcpkg install gnustep-base:x64-linux-llvm
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: installed-${{ matrix.name }}
          path: ./installed
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: buildtrees-${{ matrix.name }}
          path: ./buildtrees/**/*.log
